spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/BrightonWang/SpringCloudDemo/tree/master/NewSpringCloudDemo/
          search-paths: spring_cloud_config/config-demo
          username: username
          password: password
server:
  port: 10011
