server:
  port: 10010 # 服务端口
spring:
  application:
    name: api-gateway #制定服务名
#zuul:
#  routes:
#    user-service: #这里时路由id, 随便写
#      path: /user-service/** # 这里是映射路径
##      url: http://127.0.0.1:8081 # 映射路径对应的实际url地址
#      serviceId: user-service #指定服务名称
zuul:
  prefix: /api # 添加路由前缀
  routes:
    user-service:
      path: /service/** #这里是映射路径
#      strip-prefix: false
      serviceId: user-service
    user-consumer:
      path: /consumer/** #这里是映射路径
      serviceId: user-consumer
  host:
    connect-timeout-millis: 999999 #HTTP连接超时时间要比Hystrix的大
    socket-timeout-millis: 999998 #socket超时时间
  retryable: true #开启zuul的重试机制
  ignored-services: user-service #忽略默认匹配的path
#  ignored-patterns: /**/user-service/**
ribbon:
  ReadTimeout: 9999 #通信超时时间(ms)
  ConnectTimeout: 250 #连接超时时间(ms)
  OkToRetryOnAllOperations: true #是否对所有操作重试
  MaxAutoRetriesNextServer: 2 #同一服务不同实例的重试次数
  MaxAutoRetries: 1 #同一实例的重试次数
hystrix.command.execution.isolation.thread.timeoutInMillisecond: 6000 #熔断超时时长: 6000ms
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10088/eureka
    registry-fetch-interval-seconds: 5 # 获取服务列表的周期: 5s
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
