server:
  port: 8083
spring:
  application:
    name: user-consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10088/eureka
    fetch-registry: true #拉取Eureka Server 服务的列表只读备份，缓存在本地
    registry-fetch-interval-seconds: 5 #每隔5秒会重新获取并更新数据
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

