server:
  port: 10010 #服务端口
spring:
  application:
    name: api-gateway #指定服务名
#zuul:
#  routes:
#    user-service: /user-service/** #这里是映射路径
#    user-service: #这里是路由id,随便写
#      path: /user-service/** # 这里是映射路径
#      sericeId: user-service # 指定服务名称
#      url: http://127.0.0.1:8081 #映射路径对应的实际url地址

eureka:
  client:
    registry-fetch-interval-seconds: 5 #获取服务列表的周期:5s
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
zuul:
  prefix:  /api #添加路由前缀
  retryable: true
ribbon:
  ConnectaTimeout: 250 # 连接超时时间(ms)
  ReadTimeout: 2000 # 通信时间时间(ms)
  OkToRetryOnAllOperations: true # 是否对所有操作重试
  MaxAutoRetriesNextServer: 2 # 同一服务不同实例的重试次数
  MaxAutoRetries: 1 # 同一实例的重试次数
hystrix:
  command:
    isolation:
      thread:
        timeoutInMillisecond: 6000 # 熔断超时时长: 6000ms