server:
  port: 10087 #端口
spring:
  application:
    name: eureka-server #应用名称,会在Eureka中显示
eureka:
  client:
#    register-with-eureka: false #是否注册自己的信息到EurekaServer,默认是true
#    fetch-registry: false #是否拉取其他服务的信息,默认是true
    service-url: #EurekaServer的地址,现在是自己的地址,如果是集群,需要加上其他Server的地址
      defaultZone: http://127.0.0.1:10086/eureka
#      defaultZone: http://127.0.0.1:${server.prot}/eureka
  instance:
    lease-expiration-duration-in-seconds: 10 #10秒即过期
    lease-renewal-interval-in-seconds: 5 #5秒一次心跳
  server:
    eviction-interval-timer-in-ms: 1000 #每隔一秒对失效服务剔除
    enable-self-preservation: false  #关闭自我保护模式(缺省为打开)

