server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/brighton
    username: root
    password: 112233
    hikari:
      maximum-pool-size: 20
      minimum-idle: 10
mybatis:
  type-aliases-package: com.brighton.service.entity

