server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test
    username: root
    password: 112233
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: user-service #应用名称, 注册到eureka后的服务名称
#    hikari:
#      maximum-pool-size: 20
#      minimum-idle: 10
mybatis:
  type-aliases-package: cn.brighton.service.pojo
eureka:
  client:
    service-url: #EurekaServer地址
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    ip-address: 127.0.0.1 #指定自己的ip信息,不指定的话会自己寻找
    prefer-ip-address: true #当调用getHostnam获取实例的hostname时,返回ip而不是host名称
    instance-id: ${spring.application.name}:${server.port}
#user-service:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule